from openai import OpenAI
from flask import Flask, request, jsonify

app = Flask(__name__)
client = OpenAI()

@app.route("/ask", methods=["POST"])
def ask():
    question = request.json["question"]
    response = client.chat.completions.create(
        model="gpt-4o",
        max_tokens=500,
        messages=[{"role": "user", "content": question}],
    )
    answer = response.choices[0].message.content
    disclaimer = "This answer was generated by an AI model and may not be accurate. Always verify with trusted sources."
    return jsonify({"answer": answer + "\n\n" + disclaimer})
