# Always append a disclaimer to LLM-generated factual content
require 'openai'

MEDICAL_DISCLAIMER = "DISCLAIMER: This information is generated by an AI and is not a substitute for professional medical advice. Always consult a qualified healthcare provider."

class HealthController < ApplicationController
  def advise
    client = OpenAI::Client.new(access_token: ENV['OPENAI_API_KEY'])
    resp   = client.chat(
      parameters: {
        model:      'gpt-4o',
        max_tokens: 512,
        messages:   [
          { role: 'system', content: 'You are a general health information assistant. Do not provide specific medical diagnoses or treatments.' },
          { role: 'user',   content: params[:question] }
        ]
      }
    )
    answer = resp.dig('choices', 0, 'message', 'content')
    # SAFE — disclaimer always appended, LLM output not presented as authoritative
    render json: { response: answer, disclaimer: MEDICAL_DISCLAIMER }
  end
end
