# News article generated by LLM published without fact-checking step
require 'openai'

class NewsGenerator
  def generate_article(topic)
    client = OpenAI::Client.new(access_token: ENV['OPENAI_API_KEY'])
    resp   = client.chat(
      parameters: {
        model:    'gpt-4o',
        messages: [
          { role: 'system', content: 'Write a factual news article.' },
          { role: 'user',   content: "Write an article about: #{topic}" }
        ]
      }
    )
    content = resp.dig('choices', 0, 'message', 'content')
    # VULNERABLE — article published directly as authoritative news without human review
    Article.create!(title: topic, body: content, published: true)
  end
end
